### ISSUE TITLE
UAS: minor spelling issue

### ISSUE THREAD

**Issue by OttoKerner** [dagalufh/WebTools.bundle#101]
after existing .bundles are migrated to the UAS, the dialog box says
"Below is the migrated bundle(s)"

I have a hunch this would be in the majority of cases more than one bundle, so
"Below are the migrated bundles" 
would be more correct.

A more universal phrase would be 
"Below is the list of migrated bundles"
it wouldn't feel that weird when there is only one bundle mentioned below.

**Comment by dagalufh** [comment]
Added in upcoming commit, thanks for suggestion.

**Comment by ukdtom** [comment]
Confirmed fixed
