### ISSUE TITLE
subs: [minor] Plex libraries are referred to as 'sections'

### ISSUE THREAD

**Issue by OttoKerner** [dagalufh/WebTools.bundle#102]
When the drop-down menu with the list of Plex libraries is expanded, at the bottom it says
"Refresh Sections"

This should be changed into 
"Refresh list of Libraries"

The official use of "Sections" has been deprecated since almost 2 years now. Users shouldn't be unsettled by deviant terminology.

And this menu point should **not** be called "Refresh Libraries" because that is a whole different thing in the Plex world. https://support.plex.tv/hc/en-us/articles/200289306-Update-or-Refresh-a-Library

**Comment by dagalufh** [comment]
Fixed in upcoming commit.

**Comment by ukdtom** [comment]
Confirmed fixed
