### ISSUE TITLE
Some bundles miss their support url. Know it? Add it here

### ISSUE THREAD

**Issue by rabelux** [dagalufh/WebTools.bundle#107]
Some of the bundles just couldn't be tracken down yet. Feel free to post the link here and it will be added

**Comment by ukdtom** [comment]
Just FUI:

https://github.com/ukdtom/UAS2Res/wiki

Above git is what holds the Repo for the UAS, and is contained in this file:
https://github.com/ukdtom/UAS2Res/blob/master/Resources/plugin_details.json

**Comment by ukdtom** [comment]
Better git for this would be 

https://github.com/ukdtom/UAS2Res

Closing this
