### ISSUE TITLE
Logs module

### ISSUE THREAD

**Issue by ukdtom** [dagalufh/WebTools.bundle#108]
Would be kinda cool, if lines when viewing the log would have different colours, if a line contained the word CRITICAL and another colour for the word ERROR.

Topping it would be a Critical and Error button, that would let you scroll to the next line containing that keyword

**Comment by dagalufh** [comment]
Partial implementation, color highlighting, but not quick jump.

**Comment by ukdtom** [comment]
Confirmed so far, but will leave this open, unless you say enough is enough

Your work, your call

**Comment by ukdtom** [comment]
We need to check for the word "Exception" as well ;-)
