### ISSUE TITLE
UAS. Allow it to fetch from release info as well

### ISSUE THREAD

**Issue by ukdtom** [dagalufh/WebTools.bundle#110]
Change UAS, so it'll check/update from both Master thread, as well as from the Release

**Comment by ukdtom** [comment]
Since the UAS Repo already contains the unused value named:
"branch"          :     "master"

I take it we could use something like:
"branch"          :     {'release':'NameOfAsset'}

Above for a release, so we can get the browser_download_url from the correct asset
And if using the master branch, it would look like:
"branch"          :     {'master':None}

**Comment by ukdtom** [comment]
And if browser_download_url is not found, then simply grap the zipfile

**Comment by ukdtom** [comment]
Ohhhhh.....And when checking for update timestamps, we need to make sure we check the correct place as well

**Comment by ukdtom** [comment]
Awaits issue 120

**Comment by kolsys** [comment]
Issue #120 is closed.
What about this feature?

**Comment by ukdtom** [comment]
Not there yet, and will not make the next release, sadly

**Comment by ukdtom** [comment]
And V2.2 just released ;-)

**Comment by ukdtom** [comment]
Note to self:
Download seems to work now, but we need to make sure, that when checking for new updates, that we also check release branch for that.

And fix not checked in yet ;-)

**Comment by ukdtom** [comment]
Fixed with https://github.com/dagalufh/WebTools.bundle/commit/a9c08a1998b84ca34008ec6e477925d45e6fd637

**Comment by kolsys** [comment]
And how to configure plugin for release update mode?

**Comment by ukdtom** [comment]
Heh.....

Check the test branch of UAS Repo (Plex2CSV)

And if wanna test this already, then grab the Tommy-Work branch of WT, but you'll need to add a debug file, so WT goes for the test branch instead of the master branch

file should be named "debug" and should be located in the root of the bundle dir.
Contents like:

{
	"WT_AUTH": false, 
	"UAS_Repo": "https://github.com/ukdtom/UAS2Res", 
	"UAS_RepoBranch" : "test"
}

And in above, Pwd validation is also disabled ;-)

**Comment by ukdtom** [comment]
And it'll always got after releases/latest
