### ISSUE TITLE
Migration fails, if plugin directory contains hidden folder

### ISSUE THREAD

**Issue by ukdtom** [dagalufh/WebTools.bundle#115]
If the Plug-in directory contains a folder like  ._Plex-FindUnmatched.bundle it'll fail.

We need to ignore folders starting with a dot

**Comment by chrissearle** [comment]
The specific case here is from AppleDouble format - but - safer to ignore all "." prefixed directories

**Comment by ukdtom** [comment]
Fixed in https://github.com/dagalufh/WebTools.bundle/commit/d34e20a6a9d836b3cb7efcc3ae2f77f79ea9d06e
Slated for V2.2
