### ISSUE TITLE
UAS and uninstall unknown bundle

### ISSUE THREAD

**Issue by ukdtom** [dagalufh/WebTools.bundle#117]
Still shows up, so guess a cleanup has failed somewhere :-(

**Comment by dagalufh** [comment]
Please elaborate, do you mean after uninstall?

**Comment by ukdtom** [comment]
Yes, and assigned to me, cuz sadly suspect it's in my end here :-(

**Comment by ukdtom** [comment]
Fixed in https://github.com/dagalufh/WebTools.bundle/commit/cab8008d1d829b3db830b938fc7a67bfe90ffc27
