### ISSUE TITLE
UAS: Unknown bundle installed from Git

### ISSUE THREAD

**Issue by ukdtom** [dagalufh/WebTools.bundle#118]
Has a valid github link, so we should still have the button on it to check for updates

**Comment by ukdtom** [comment]
We also should have the button to check for the last update time ;-)

**Comment by dagalufh** [comment]
I've looked into this.
I did a manual install of afdah; that should have caused it to have the github for later usage.
But when looking at the resulting object i get back when checking unknowns:

branch: ""
bundle: "Afdah.bundle"
date: "2016-01-26 10:26:44"
description: ""
icon: ""
identifier: "com.plexapp.plugins.afdah"
title: "Afdah"
type: Array[1]
0: "Unknown"

There is no mention of the gitlink.

**Comment by shoguevara** [comment]
Hi! I Have about 8 addons installed manually for Plex. I tried to sync it with WebTools database, but now I have 6 addons that has no title and it's impossible to delete them from WT. It doesn't matter whether plugin files are still existing inside plugins folder or not. 
Is it the same issue, or should I start another bug report?
This is what I get when trying to delete such plugins:
Errorinfo:
Requested URL: /webtools2?module=pms&function=delBundle&bundleName=
Error Code/Message: 412/Precondition Failed

WebTools logs are showing only that delete request received and no further info.

**Comment by ukdtom** [comment]
What's the name of the bundle?

**Comment by shoguevara** [comment]
https://github.com/CatmanIX/UnSupportedAppstore.bundle 
 https://github.com/plexinc-agents/Kinopoisk.bundle 
https://github.com/achuprin/turboplex 
https://github.com/jwsolve/HDMoviesDownload.bundle 
https://github.com/plexinc-plugins/TuneIn.bundle 
https://github.com/aamkTV/CokeandPopcorn.bundle 

Some of theese are still working fine (like tunein, kinopoisk or UnSupportedAppstore by CatmanIX), but the name field for all of them are empty/ That causes errors on installation.
Here's the screenshot http://pasteboard.co/15nDn3kK.png

**Comment by ukdtom** [comment]
@dagalufh It should be the key, and not in the value, or?

**Comment by ukdtom** [comment]
@shoguevara Working fine here, so suspect something else.
Please create a separate issue, and provide full logs from WebTools

**Comment by dagalufh** [comment]
@ukdtom key is the same as identifier, and that's no git link..

**Comment by ukdtom** [comment]
And @shoguevara 

FUI: the CatmanIX UAS is not to be used, IMHO, since it's a clone of the origin UAS, and if it get's popular, then Github will close it, like they did with the original UAS, since it's still buggy.
Besides that, all bundles in there, is also in here, and here devs are adding new stuff

**Comment by CatmanIX** [comment]
@shoguevara using my appstore at the same time as the new one is just begging for conflicts and issues. I'll probably be removing that soon now that i'm aware UASv2 exists. I threw that up temporarily when UAS disappeared and i wanted to add a couple bundles. I was surprised anyone else actually used it, lol.

**Comment by shoguevara** [comment]
Used UAS by @CatmanIX just to check what bundles the package contains. To tell the truth never used it to install any plugins, as all I need I already installed manually. 
So, don't pay attention to that particular plugin, guys =)

**Comment by dagalufh** [comment]
@ukdtom has this been fixed so i can implement it?

**Comment by ukdtom** [comment]
If installed, then the key has it.
If migrated, then it for sure is unknown.

So the answer is yes

**Comment by shoguevara** [comment]
I did a bit more digging and found interesting fact - the error I mentioned before happens when I manually add bundle from github, with the same name as it is in WT? but from another users hub. In this case stale records appears in the installed plugin list. But the funny thing is, that those stale records are the ones should've been managed, but not the records added by WT from it's database.
So, I guess I need to open another issue.

**Comment by dagalufh** [comment]
Included in latest commit on micke-work.
