### ISSUE TITLE
UAS: Multiple update channels (master, beta, develop)

### ISSUE THREAD

**Issue by fuzeman** [dagalufh/WebTools.bundle#120]
Roughly this would involve the following additions/changes:
 - Parameter added to define available update channels (and labels) in plugin details, for example: ```{"master": "Stable", "beta": "Beta", "develop: "Development"}```
 - Controls to change/select the update channel on plugins
    - Drop-down to select update channel for new installs
    - Drop-down + button to change the update channel for existing plugins (this will also re-install the plugin from the selected channel)
    - Store selected update channel in ```Dict['installed']```
 - Changes to ```git``` class to support update channel selection

-----------------------

Don't mind working on this myself and sending through a PR, just interested what your thoughts are before starting on anything.

**Comment by ukdtom** [comment]
Well......To be frank, I suspect only Trakt use this ;-)

And do have this one open:
https://github.com/dagalufh/WebTools.bundle/issues/110

But do go ahead, and start working on it, and suggest you use the tommy-work branch as foundation here, since the backend is most updated in that branch

/T

**Comment by ukdtom** [comment]
And if so, then do remember to update the odt doc in Code/Docs as well, so the frontend knows what to call

**Comment by ukdtom** [comment]
Ohh....And maybe:

{"master": {"Stable" : True}, "beta": {"Beta":False}, "develop: {"Development":False}}

With above, Gui would lnow what the default was

**Comment by ukdtom** [comment]
And even better:

{"master": {"Stable" : True}, "beta": {"Beta":False}, "develop: {"Development":False}, "release":{"assetName":False}}

With the last one, we also nails issue 110, so......

Are you up for the task?

**Comment by fuzeman** [comment]
Happy to work on this, but would probably need to leave it to next week before I have some time to work on it.

**Comment by ukdtom** [comment]
NP, and looking forward, cuz as you might have noticed, when looking @ my code so far, I'm not a professional developer, so my implementation to this would end up working, but would be kinda basic ;-)

So looking forward for your magic here ;-)

**Comment by fuzeman** [comment]
Finally had some time to work on this feature, check out my [feature/update-channels](https://github.com/fuzeman/WebTools.bundle/tree/feature/update-channels) branch (based off the ```micke-work``` branch) for the current implementation.

Let me know if you find any issues with the implementation, happy to make any changes as needed.

--------------------------------

**UI:**
![](https://i.imgur.com/OKFvwzo.png)

**Comment by fuzeman** [comment]
Format of plugin details is:
```json
    {
        "title"           :     "Trakt.tv",
        "bundle"          :     "Trakttv.bundle",
        "type"            :     ["Application", "Social"],
        "description"     :     "Keep track of TV shows and movies you watch, synchronize your watched history and ratings between applications, and use the trakt.tv website to see upcoming episodes on a calendar, participate in the community and discover new TV shows and movies.",
        "repo"            :     "https://github.com/trakt/Plex-Trakt-Scrobbler",
        "branches"        :     [
            {"name": "master", "label": "Stable"},
            {"name": "beta", "label": "Beta"}
        ],
        "identifier"      :     "com.plexapp.plugins.trakttv",
        "icon"            :     "trakt-icon.png",
        "supporturl"      :     "https://forums.plex.tv/discussion/102818"
    },
```

**Note:** Only plugins that want to use multiple update channels needs the "branches" parameter, the previous "branch" parameter will be used as a fallback.

**Comment by ukdtom** [comment]
Could be off track here, but don't you think we would need something indicating the default branch, that people should use, and make that preselected in the combo?

After all, most users has no clue as to what branch to select, or?

/T

**Comment by fuzeman** [comment]
> Could be off track here, but don't you think we would need something indicating the default branch, that people should use, and make that preselected in the combo?

The first item in the "branches" list is currently the default.

Having a separate option would mean you could change the position (in the list) of the default branch, not sure how useful that would be though?

**Comment by ukdtom** [comment]
Makes sense, and didn't spot that ;-)

Your code is flawless, so do go ahead, and make a PR against my thread

**Comment by ukdtom** [comment]
Fix checked in https://github.com/dagalufh/WebTools.bundle/commit/0081275ee78ffef6b1c5e2c2e5e3edea6d0ef906

Thanks

**Comment by ukdtom** [comment]
Sadly broke manual install of a bundle, that's not in UAS, SNIFF

**Comment by ukdtom** [comment]
And correction here, it's all manual installs, regardless of been in uas or not

**Comment by fuzeman** [comment]
> Sadly broke manual install of a bundle, that's not in UAS, SNIFF

Woops, forgot about manual installations. Will work on getting this fixed now.

**Comment by fuzeman** [comment]
Should be fixed with #153, let me know if you find any other issues :smile:

**Comment by ukdtom** [comment]
Looks cool, and thanks....

Ohhhh....And your PR against UAS2Res......

Wanna update that with the branch stuff perhaps?

/T

**Comment by ukdtom** [comment]
Changed lost!

**Comment by ukdtom** [comment]
Fixed by @dagalufh in https://github.com/dagalufh/WebTools.bundle/commit/ac2aca791e96a2d161d6d6c8c6e4ff75c52972e4
