### ISSUE TITLE
UAS: Cleanup old files/folders when updating

### ISSUE THREAD

**Issue by fuzeman** [dagalufh/WebTools.bundle#121]
Overwriting plugins can cause conflicts in some cases (example below), ideally an update should compare the currently installed plugin with the new version (zip) and delete any directories/files that have been removed.

#### Example

**Example.bundle (v1.0.0)**
```
Example.bundle
 - Contents
    - Code
       - [...]
 - Libraries
   - example
      - one
         - __init__.py
```

**Example.bundle (v1.1.0)**
```
Example.bundle
 - Contents
    - Code
       - [...]
 - Libraries
   - example
      - one.py
```

**Result**
```
Example.bundle
 - Contents
    - Code
       - [...]
 - Libraries
   - example
      - one
         - __init__.py
      - one.py
```

Attempting to import ```example.one``` will always return the ```example/one/__init__.py``` module, there is no way to access the updated module.

--------------

This was mentioned here as well: https://forums.plex.tv/discussion/comment/1106806/#Comment_1106806

**Comment by ukdtom** [comment]
Fixed checked in
https://github.com/dagalufh/WebTools.bundle/commit/cab8008d1d829b3db830b938fc7a67bfe90ffc27
