### ISSUE TITLE
UAS: Inform users directly, if permission error

### ISSUE THREAD

**Issue by ukdtom** [dagalufh/WebTools.bundle#124]
If on Linux, and permissions are not okay to create the UAS dir, we should tell the user directly on the screen.

Otherwise, we'll have the same Q again and again in the support thread

**Comment by ukdtom** [comment]
Fixed in the backend, so please make sure, that frontend can handle a multiline response

**Comment by ukdtom** [comment]
Linux, if no rights to create the uas directory.
STD: Create the dir, and then change it's rights.

Then nuke data/cache, and call UpdateUASCache

**Comment by dagalufh** [comment]
So it's on UpdateUASCache that you return the error in question?

**Comment by ukdtom** [comment]
Yep....git.py line 266 and onwards

**Comment by ukdtom** [comment]
To test, add this line 

				try:
					Core.storage.ensure_dirs(targetDir)
					raise ValueError('Errno 13')            <------   ADD THIS
				except Exception, e:
					errMsg = str(e)
					if 'Errno 13' in errMsg:

**Comment by dagalufh** [comment]
Implemented this message.
