### ISSUE TITLE
UAS: Allow WebTools to autoupdate

### ISSUE THREAD

**Issue by ukdtom** [dagalufh/WebTools.bundle#126]
We update every other plugin, so we should look into WebTools as well

**Comment by ukdtom** [comment]
Avaits https://github.com/dagalufh/WebTools.bundle/issues/120

**Comment by ukdtom** [comment]
Backend fixed with https://github.com/dagalufh/WebTools.bundle/commit/c6ff5808948919737775362411a7f0fab0789873

Now needs so frontend work here.

See the doc in the commit

**Comment by ukdtom** [comment]
Fixed without 3.Party

**Comment by dagalufh** [comment]
Included in next update.

**Comment by ukdtom** [comment]
Confirmed
