### ISSUE TITLE
WebTools: Changelog

### ISSUE THREAD

**Issue by ukdtom** [dagalufh/WebTools.bundle#128]
Since we store the complete changelog, but on the front page only show the latest, then maybe a menu option to show the complete one?

**Comment by ukdtom** [comment]
Does it makes sence to have this under the logs menu?

My bet, options would be a better place, so reopening
But feel free to shoot me down in flames, and reclose ;-)

**Comment by dagalufh** [comment]
Moved in the last commit to micke-work.
