### ISSUE TITLE
Adding bundle, that already was in WT database from another users hub leads to stale record creation

### ISSUE THREAD

**Issue by shoguevara** [dagalufh/WebTools.bundle#130]
Let's say, there is a bundle, which WT is aware of. We can take tunein.budle for example. WT refers to https://github.com/solvek/TuneIn.bundle to download it and install. But, for some reason, I need to install the bundle with the same name, but from another source. For example, from here https://github.com/plexinc-plugins/TuneIn.bundle.
If I do install the bundle from the second location, I mean from plexinc-plugins hub (still using WT to do that), while WT is referencing to solvek's hub, and after that I initiate migration of previously installed plugins (let's say I have a couple installed manually), as the result I get two records in installed plugins database. 
First one has no package name and any other info, besides github URL and install date and it refers to the right repo. But it is impossible to delete, reinstall or update it - it throws an error, because there is no bundle name.
Second one is OK, and WT even lets to delete this bundle and the record disappears... But the first record remains.
So, in this situation, we have no plugin installed and have stale record about it, that couldn't be removed.
Only way I found to resolve this is to delete WebTools preferences.
Unfortunately, I found noting suspicious in logs...
The screenshot is here http://pasteboard.co/15nDn3kK.png

**Comment by ukdtom** [comment]
Fixed with https://github.com/dagalufh/WebTools.bundle/commit/1699c609d9fa644058cf8c88a9093e421b2fc912
