### ISSUE TITLE
UAS: Wrong time for Latest Update on Github

### ISSUE THREAD

**Issue by pax0707** [dagalufh/WebTools.bundle#134]
Example:

Plex Request Channel
Latest Update on Github: 	2016-02-07 18:50:48

Latest commit 9c72deb  39 minutes ago @ngovil21 ngovil21 Merge branch 'development'  40 minutes ago    

That would be around 1:50AM CET for me.

Guess something with time zone detection.

**Comment by ukdtom** [comment]
Fixed in https://github.com/dagalufh/WebTools.bundle/commit/e12ed1d0933cf428167d9e299a2b6747f2a33dce

Switched to Commit Id instead of timestamps when comparing.
Only future installs/checks will work the new way
Already installed plugin's continue the old way, until checked for updates
