### ISSUE TITLE
Fail to start on ASUSTOR NAS

### ISSUE THREAD

**Issue by RRocks01** [dagalufh/WebTools.bundle#136]
I have dropped the WebTools.bundle-2.1 folder into my PMS plugins folder and restarted plex, and tried rebooting the NAS and the button just does not show up in plex.  I know I have the folder in the correct place as its the same plugin folder where I have my HDHomeRunVIiew plugin which works fine.  I also know that the contents folder is only one level down from the webtools folder I dropped in.  Any help?

**Comment by RRocks01** [comment]
incase anyone else had this problem I realized my mistake right after I hit post.. the bundle folder has the -2.1 in the folder name, once i removed that the button showed up right away.

**Comment by ukdtom** [comment]
:-)

And huge thanks for returning here, and explaining so others might avoid this

/T
