### ISSUE TITLE
UAS: click on "Show only installed", then migrate

### ISSUE THREAD

**Issue by ukdtom** [dagalufh/WebTools.bundle#140]
After doing so, only categories where we have installed bundles in are now shown.
(Guess that's a leftover from a previous ghi, that we reverted from)

But problem is, that unchecking the combo does nothing for the missing categories.
One has to leave uas, and go back in to make them show

**Comment by dagalufh** [comment]
Fixed in next update.

**Comment by ukdtom** [comment]
Confirmed
