### ISSUE TITLE
Feature Requests - Add Jump To Top button in Log Viewer - Search

### ISSUE THREAD

**Issue by trumpy81** [dagalufh/WebTools.bundle#142]
When viewing long log files such as those found in Plex, it would b nice to have a button on the bottom of the screen to allow you to quickly jump back to the top of the page so that you can select another log file.

Or alternatively, move the log selection menu to the top toolbar or make it static on the screen.

Also, the ability to be able to search the log file being viewed for keywords would be nice. :)

**Comment by ukdtom** [comment]
Regarding a jump button, maybe also extended with a "Jump to Error/Critical" ?

**Comment by trumpy81** [comment]
Yeah that would also be helpful :)

**Comment by dagalufh** [comment]
This will be in the next update.

**Comment by ukdtom** [comment]
Confirmed okay
