### ISSUE TITLE
WT: Language module

### ISSUE THREAD

**Issue by ukdtom** [dagalufh/WebTools.bundle#143]
Make a language module, that can extract stuff regarding supported languages by PMS

**Comment by ukdtom** [comment]
Backend done, now for the frontend....
Check the docs

**Comment by dagalufh** [comment]
Would it be possible for your to change it from:
{"en":"English"}
to:
{en:"English"} ?

Just to keep you busy, otherwise i'll have to do some corrections.

**Comment by ukdtom** [comment]
That would produce an invalid json ;-)
http://www.json.org/

**Comment by ukdtom** [comment]
Confirmed fixed
