### ISSUE TITLE
[SM] finding a particular movie to delete subtitles is painful with larger libraries

### ISSUE THREAD

**Issue by OttoKerner** [dagalufh/WebTools.bundle#146]
Imagine a movie library with several hundreds of movies in it.
Somewhere in the middle of this list is a movie for which the opensubtitles agent downloaded some wrong subtitles.
How do I find this movie?

Right now, I have to page through dozens of screen pages until I find my movie.
This is cumbersome and frustrating.

I can imagine 2 approaches to improve "the user experience":

# shorten the movie list
There are already filters available to exclude internal subtitles. But they only remove the subtitles from the whole list. 
How about removing all the movies from the list which don't fit my filter? (e.g. show me only those movies which actually have external or agent-supplied subtitles)

# make the paging dropdown 'smarter'
Right now, the dropdown to quickly jump to a particular page in the movie list only shows a page number. This is not very helpful, since I can't figure out quickly, on which screen page my 'target movie' would appear.
![pager](https://cloud.githubusercontent.com/assets/10280992/13890452/d964cb80-ed4b-11e5-95ad-7ab6fbb5e55d.png)

How about not only showing a 'page' number, but also the first 3 letters of the first movie title on that page? (actually, use the 'sort title' to mirror the order of Plex Web)
Navigation/paging would be much more targeted and thus quicker.

**Comment by ukdtom** [comment]
Too late for V2.2, so slated for next version instead.

Sadly, this involves both a change to the backend, as well as to the frontend.

And backend has to be done first, so assigned to me

**Comment by ukdtom** [comment]
* Backend needs to produce an alphabetic list of titles avail in a section
* Backend needs to provide a lookup for a letter https://github.com/dagalufh/WebTools.bundle/issues/148
* Backend needs to provide a way to lookup a section based on first letter
https://github.com/dagalufh/WebTools.bundle/issues/149

**Comment by ukdtom** [comment]
Backend: https://github.com/dagalufh/WebTools.bundle/commit/15a5179b3a3a870804ecdfa2db687bbf063df523 and https://github.com/dagalufh/WebTools.bundle/issues/148

**Comment by ukdtom** [comment]
Made smarter in the latest build, and sadly as good as it gets for now
