### ISSUE TITLE
LV - Search does not react to enter

### ISSUE THREAD

**Issue by trumpy81** [dagalufh/WebTools.bundle#147]
First off, the search function and jump to top button is awesome! :)

However, I noticed that when entering a search term, pressing enter does not initiate a search, you must click on the search keyword button before it will search.

Is this a bug or a limitation?

**Comment by dagalufh** [comment]
It's a mistake from me, it will be fixed in next version. :)

**Comment by trumpy81** [comment]
Kewl, thanks. :)

I will be waiting for the next version with baited breath ... lol :)

**Comment by ukdtom** [comment]
Confirmed fixed

**Comment by trumpy81** [comment]
Confirmed fixed here too. Thank you. :)
