### ISSUE TITLE
UAS - Reporting Duplicate bundles

### ISSUE THREAD

**Issue by trumpy81** [dagalufh/WebTools.bundle#151]
I installed WT 2.2 on my Synology NAS and opened UAS.

YouTubeTV.bundle had been installed manually some time ago. I added the address into the auto install field - https://github.com/kolsys/YouTubeTV.bundle

WT installed the bundle but I was left with 2 copies of the same bundle under unknown bundles. I checked the plug-ins folder, but only one copy existed.

I tried to update the bundle from WT by clicking on the check for update, but the Latest Update on Github:  -  field changed on the other copy of the bundle, WTF?

I'm not entirely sure what happened there, but I ended up deleting both copies and reinstalling, all is fine afterwards.

I have grabbed the WT logs manually and attached them here:
[PMS Plugin Logs.zip](https://github.com/dagalufh/WebTools.bundle/files/180457/PMS.Plugin.Logs.zip)

**Comment by trumpy81** [comment]
After installing WT with Chucks .spk, I overwrote the 2.1 WebTools.bundle folder with the 2.2 folder and as a consequence, I had to delete the Plug-in Support/Cache/WebTools folder etc.

After launching WT and entering UAS I used the 'Migrate Manually/Previously Installed Channels' I again got the duplicate entries shown under Unknown, as can be seen in the image below.

![untitled-1](https://cloud.githubusercontent.com/assets/12381786/14226165/1278ba94-f91d-11e5-8a42-80a1f75394a0.jpg)

**Comment by ukdtom** [comment]
Can be fixed with the new "Reset to factory std." option
