### ISSUE TITLE
Logs [enhancement] Ability to pull WebClient logs with other server and plug-in logs

### ISSUE THREAD

**Issue by ChuckPa** [dagalufh/WebTools.bundle#155]
When pulling logs from Plex,  WebClient logs are often needed with Server logs.
The ability to pull the WebClient logs with the other logs would avoid having to go in and manually grab them.

**Comment by ukdtom** [comment]
Sadly, the WebClient logs are not present in the filesystem, but stored in cache on the individual browsers, and as such, this enhancement can't be done
