### ISSUE TITLE
WT 2.2 - Issues on PC

### ISSUE THREAD

**Issue by trumpy81** [dagalufh/WebTools.bundle#157]
As instructed by Tommy, I copied the files into the WebTools.bundle folder and simply overwrote the existing files.

When I opened WT in the browser, I signed in and all seemed well. Upon opening UAS, I checked for the option to select a theme, but no such option is displayed.

When opening the LV, I see the loading dialogue but the log file never loads. See image:
![untitled-1](https://cloud.githubusercontent.com/assets/12381786/14520562/8dfde79e-0268-11e6-9656-ab7253c48985.jpg)

I closed and then reopened WT in the browser, but again, when entering LV, it gets stuck loading the default log file and never displays the log file.

I removed WebTools.bundle completely, including the folders in /Plug-in Support/Cache and Data and reinstalled the latest WebTools.bundle. (I used the same bundle on the Synology NAS).

There was no change in behaviour or any other details and still no theme select option and the endless loading of the default log file.

WT Logs: [WT-Logs.zip](https://github.com/dagalufh/WebTools.bundle/files/218618/WT-Logs.zip)

**Comment by ukdtom** [comment]
WT Log shows:
`2016-04-14 17:32:07,834 (2590) :  DEBUG (logkit:13) - Returning [u'Plex DLNA Server Neptune.log', u'Plex DLNA Server Neptune.old.log', u'Plex DLNA Server.1.log', u'Plex DLNA Server.2.log', u'Plex DLNA Server.3.log', u'Plex DLNA Server.4.log', u'Plex DLNA Server.5.log', u'Plex DLNA Server.log', u'Plex Media Scanner Analysis.1.log', u'Plex Media Scanner Analysis.2.log', u'Plex Media Scanner Analysis.3.log', u'Plex Media Scanner Analysis.4.log', u'Plex Media Scanner Analysis.5.log', u'Plex Media Scanner Analysis.log', u'Plex Media Scanner.1.log', u'Plex Media Scanner.2.log', u'Plex Media Scanner.3.log', u'Plex Media Scanner.4.log', u'Plex Media Scanner.5.log', u'Plex Media Scanner.log', u'Plex Media Server.1.log', u'Plex Media Server.2.log', u'Plex Media Server.3.log', u'Plex Media Server.4.log', u'Plex Media Server.5.log', u'Plex Media Server.log', u'com.plexapp.agents.fanarttv.log', u'com.plexapp.agents.fanarttv.log.1', u'com.plexapp.agents.fanarttv.log.2', u'com.plexapp.agents.fanarttv.log.3', u'com.plexapp.agents.fanarttv.log.4', u'com.plexapp.agents.fanarttv.log.5', u'com.plexapp.agents.htbackdrops.log', u'com.plexapp.agents.htbackdrops.log.1', u'com.plexapp.agents.htbackdrops.log.2', u'com.plexapp.agents.htbackdrops.log.3', u'com.plexapp.agents.htbackdrops.log.4', u'com.plexapp.agents.htbackdrops.log.5', u'com.plexapp.agents.imdb.log', u'com.plexapp.agents.imdb.log.1', u'com.plexapp.agents.imdb.log.2', u'com.plexapp.agents.imdb.log.3', u'com.plexapp.agents.imdb.log.4', u'com.plexapp.agents.imdb.log.5', u'com.plexapp.agents.lastfm.log', u'com.plexapp.agents.lastfm.log.1', u'com.plexapp.agents.lastfm.log.2', u'com.plexapp.agents.lastfm.log.3', u'com.plexapp.agents.lastfm.log.4', u'com.plexapp.agents.lastfm.log.5', u'com.plexapp.agents.localmedia.log', u'com.plexapp.agents.localmedia.log.1', u'com.plexapp.agents.localmedia.log.2', u'com.plexapp.agents.localmedia.log.3', u'com.plexapp.agents.localmedia.log.4', u'com.plexapp.agents.localmedia.log.5', u'com.plexapp.agents.lyricfind.log', u'com.plexapp.agents.lyricfind.log.1', u'com.plexapp.agents.lyricfind.log.2', u'com.plexapp.agents.lyricfind.log.3', u'com.plexapp.agents.lyricfind.log.4', u'com.plexapp.agents.lyricfind.log.5', u'com.plexapp.agents.movieposterdb.log', u'com.plexapp.agents.movieposterdb.log.1', u'com.plexapp.agents.movieposterdb.log.2', u'com.plexapp.agents.movieposterdb.log.3', u'com.plexapp.agents.movieposterdb.log.4', u'com.plexapp.agents.movieposterdb.log.5', u'com.plexapp.agents.none.log', u'com.plexapp.agents.none.log.1', u'com.plexapp.agents.none.log.2', u'com.plexapp.agents.none.log.3', u'com.plexapp.agents.none.log.4', u'com.plexapp.agents.none.log.5', u'com.plexapp.agents.omdbapi.log', u'com.plexapp.agents.opensubtitles.log', u'com.plexapp.agents.opensubtitles.log.1', u'com.plexapp.agents.opensubtitles.log.2', u'com.plexapp.agents.opensubtitles.log.3', u'com.plexapp.agents.opensubtitles.log.4', u'com.plexapp.agents.plexmusic.log', u'com.plexapp.agents.plexmusic.log.1', u'com.plexapp.agents.plexmusic.log.2', u'com.plexapp.agents.plexmusic.log.3', u'com.plexapp.agents.plexmusic.log.4', u'com.plexapp.agents.plexmusic.log.5', u'com.plexapp.agents.plexthememusic.log', u'com.plexapp.agents.plexthememusic.log.1', u'com.plexapp.agents.plexthememusic.log.2', u'com.plexapp.agents.plexthememusic.log.3', u'com.plexapp.agents.plexthememusic.log.4', u'com.plexapp.agents.plexthememusic.log.5', u'com.plexapp.agents.rottentomatoes.log', u'com.plexapp.agents.rottentomatoes.log.1', u'com.plexapp.agents.rottentomatoes.log.2', u'com.plexapp.agents.rottentomatoes.log.3', u'com.plexapp.agents.rottentomatoes.log.4', u'com.plexapp.agents.rottentomatoes.log.5', u'com.plexapp.agents.themoviedb.log', u'com.plexapp.agents.themoviedb.log.1', u'com.plexapp.agents.themoviedb.log.2', u'com.plexapp.agents.themoviedb.log.3', u'com.plexapp.agents.themoviedb.log.4', u'com.plexapp.agents.themoviedb.log.5', u'com.plexapp.agents.thetvdb.log', u'com.plexapp.agents.thetvdb.log.1', u'com.plexapp.agents.thetvdb.log.2', u'com.plexapp.agents.thetvdb.log.3', u'com.plexapp.agents.thetvdb.log.4', u'com.plexapp.agents.thetvdb.log.5', u'com.plexapp.agents.vevo.log', u'com.plexapp.agents.vevo.log.1', u'com.plexapp.agents.vevo.log.2', u'com.plexapp.agents.vevo.log.3', u'com.plexapp.agents.vevo.log.4', u'com.plexapp.agents.vevo.log.5', u'com.plexapp.plugins.cbs.log', u'com.plexapp.plugins.findUnmatch.log', u'com.plexapp.plugins.findUnmatch.log.1', u'com.plexapp.plugins.findUnmatch.log.2', u'com.plexapp.plugins.findUnmatch.log.3', u'com.plexapp.plugins.findUnmatch.log.4', u'com.plexapp.plugins.findUnmatch.log.5', u'com.plexapp.plugins.historychannel.log', u'com.plexapp.plugins.onlinemoviespro.log', u'com.plexapp.plugins.Plex2csv.log', u'com.plexapp.plugins.Plex2csv.log.1', u'com.plexapp.plugins.Plex2csv.log.2', u'com.plexapp.plugins.Plex2csv.log.3', u'com.plexapp.plugins.Plex2csv.log.4', u'com.plexapp.plugins.WebTools.log', u'com.plexapp.plugins.WebTools.log.1', u'com.plexapp.plugins.WebTools.log.2', u'com.plexapp.plugins.WebTools.log.3', u'com.plexapp.plugins.WebTools.log.4', u'com.plexapp.plugins.WebTools.log.5', u'com.plexapp.plugins.youtube.tv.log', u'com.plexapp.plugins.youtube.tv.log.1', u'com.plexapp.plugins.youtube.tv.log.2', u'com.plexapp.plugins.youtube.tv.log.3', u'com.plexapp.plugins.youtube.tv.log.4', u'com.plexapp.plugins.youtube.tv.log.5', u'com.plexapp.system.log', u'com.plexapp.system.log.1', u'com.plexapp.system.log.2', u'com.plexapp.system.log.3', u'com.plexapp.system.log.4', u'com.plexapp.system.log.5']
`

So either a local browser issue, or frontend, or ?

**Comment by dagalufh** [comment]
I would like you to test on another browser, and clear the cache for the browser in question.

Since you didn't get the theme option, that suggest to me that there is a caching issue.

**Comment by ukdtom** [comment]
Ohhh...and forgot, is there an entry in the changelog saying:
#93 WT: Now has support for custom themes! First out is a draft of trumpy81 that needs to be finetuned by trumpy81

And if not, try and reapply again

**Comment by trumpy81** [comment]
OK, I opened WT for the PC in IE 11 and the theme option appears but with the full path displayed to the second option. See the image:
![untitled-1](https://cloud.githubusercontent.com/assets/12381786/14541585/0cfa5c20-02ce-11e6-8069-e60de84b1830.jpg)

And no problem opening LV in IE 11. It works in Edge also, but does not work in FF??

**Comment by ukdtom** [comment]
Ghost in the machine?

**Comment by trumpy81** [comment]
Uhuh ... I think so ... that damn gremlin painted on my bike is trying to tell me something ... lol

**Comment by dagalufh** [comment]
Has this issue been resolved or is it still valid?

**Comment by trumpy81** [comment]
Still valid for the full path being shown in the theme selector, but only on PC.

**Comment by dagalufh** [comment]
Are you using different browsers?

Regarding full path being shown, that is something that @ukdtom  will have to check when he gets back. He does not return full path for unix links.

I haven't tested yet on my windows machine, i'll do that tonight.

When you press the Set Theme button, does anything happen in the console?
Is there anything in the WebTools log?

If you inspect the page, check the header tag. When setting a new theme, it should be updated with a new stylesheet link.

**Comment by ukdtom** [comment]
Did you check on Windows yet?

**Comment by trumpy81** [comment]
Using the theme selector with WT installed on the PC, no change in preview is shown, no change is made and no error messages are show although the selector appears to operate correctly.

It may possibly be linked to the full path being shown in the drop down?

Page headers before:

<html lang="en">
<head>
<title>WebTools</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="icon" type="image/x-icon" href="icons/favicon.ico">

<link href="css/bootstrap.min.css" rel="stylesheet">
<link href="css/default.css" rel="stylesheet">
<link id="ModuleCSS" href="" rel="stylesheet">
<script type="text/javascript" src="jscript/jquery-2.1.1.min.js"></script>
<script type="text/javascript" src="jscript/bootstrap.min.js"></script>
<script type="text/javascript" src="jscript/jquery.md5.js"></script>
<script type="text/javascript" src="jscript/asynchelper.js"></script>
<script type="text/javascript" src="jscript/functions.js"></script>
</head>
<script>
$(document).ready(function() {
// Initial bootup
webtools.log('Application started', 'Core');
webtools.list_modules.start();
});
</script>
<body>

And after:

<html lang="en">
<head>
<title>WebTools</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="icon" type="image/x-icon" href="icons/favicon.ico">

<link href="css/bootstrap.min.css" rel="stylesheet">
<link href="css/default.css" rel="stylesheet">
<link id="ModuleCSS" href="" rel="stylesheet">
<script type="text/javascript" src="jscript/jquery-2.1.1.min.js"></script>
<script type="text/javascript" src="jscript/bootstrap.min.js"></script>
<script type="text/javascript" src="jscript/jquery.md5.js"></script>
<script type="text/javascript" src="jscript/asynchelper.js"></script>
<script type="text/javascript" src="jscript/functions.js"></script>
</head>
<script>
$(document).ready(function() {
// Initial bootup
webtools.log('Application started', 'Core');
webtools.list_modules.start();
});
</script>
<body>

**Comment by ukdtom** [comment]
Fix checked in, so no long path is shown anymore
