### ISSUE TITLE
WT 2.2 - Issue on Synology NAS

### ISSUE THREAD

**Issue by trumpy81** [dagalufh/WebTools.bundle#158]
As with the PC, I copied the WebTools.bundle contents to the Synology NAS and overwrote the files. I used the same source files that I used for the PC but I get very different results on each platform?

Open WebTools in the browser, signed in and all looks fine. Went to select a custom theme but only one option is available. See the image:
![untitled-2](https://cloud.githubusercontent.com/assets/12381786/14520867/fba0a7ae-0269-11e6-985f-49dda599a9b7.jpg)

No other issues to report. :)

**Comment by dagalufh** [comment]
Can you toss up the WT log?

**Comment by ukdtom** [comment]
Also, what's in the http/custom_themes folder?

**Comment by trumpy81** [comment]
I now see WT on the Syno with the following in FF:
![untitled-2](https://cloud.githubusercontent.com/assets/12381786/14541941/c55861b2-02cf-11e6-8dae-f23fed811e51.jpg)

I think my FF is possessed ... lol 

WT-Logs: [WT-Logs.zip](https://github.com/dagalufh/WebTools.bundle/files/219859/WT-Logs.zip)

**Comment by trumpy81** [comment]
Well everything seems to be working well in WT for Syno, so I will close this one.
