### ISSUE TITLE
LV - Search for 'Warn' returns all lines

### ISSUE THREAD

**Issue by trumpy81** [dagalufh/WebTools.bundle#159]
When searching a log file for the word 'warn', if no match is found then it returns with all lines matched.

Also, is it possible to use a console font for viewing the log?

**Comment by ukdtom** [comment]
Confirmed :-)

**Comment by dagalufh** [comment]
I'll look into it and see what might be the cause of this and get back to you.

**Comment by dagalufh** [comment]
Download latest and try from my branch; https://github.com/dagalufh/WebTools.bundle/tree/micke-work

**Comment by trumpy81** [comment]
Works on PC, but still returns all lines when not found on Synology.

**Comment by dagalufh** [comment]
That sounds like a caching issue. Can you please clear the cache of your browser accessing the Synology?

Also, verify that the source code on on functions.js accessible via view source, contains this on line 719:
if ($(':nth-child(2)', this).html().toLowerCase().indexOf($('#webtoolssearchKeyword').val().toLowerCase()) != -1) {


That is the latest and the one that fixes above issue.

**Comment by trumpy81** [comment]
Looks like it may have been another browser cache issue. I tried again after clearing the browser caches and restarting the browser and it now works correctly on both Synology and PC.

**Comment by dagalufh** [comment]
Sweet, So, are we happy now or do you want this issue to remain open? :)

**Comment by trumpy81** [comment]
I'm happy, we can close this one out. :)
