### ISSUE TITLE
WT 2.2 - Themes - Request for element isolation

### ISSUE THREAD

**Issue by trumpy81** [dagalufh/WebTools.bundle#161]
When customising a style sheet the following lines control the text colour of the Log File select drop down and also the search text box text colour in the LV.

.panel-default>.panel-heading {background-color: #0082e6; color: #003a66;}
.navbar {margin-bottom: 0px;}
.navbar-default {background-color: #00477e; color: #003a66; border: 0px solid #00477e;}

If the above text colours (color:) are set to white or any other light colour, then the text is not displayed correctly, or at all, in the drop down or search text box.

I would like to see those two elements either isolated, so that no style is applied, or allow separate styles to be applied if that is at all possible, thanks. :)

Also, in the UAS, when clicking on any button and then moving the mouse pointer away from the button, the colours are not restored to those of the style sheet and instead display a default grey background with black text. If you then click on the page, the configured colours are restored. See the image.

![untitled-4](https://cloud.githubusercontent.com/assets/12381786/14578283/df74c4f8-03c6-11e6-8e5d-7004c00d3d90.jpg)

**Comment by dagalufh** [comment]
I'll look into it, Currently if i remember correctly, there is no specific css for the dropdown.

**Comment by dagalufh** [comment]
Do you mean:
![image](https://cloud.githubusercontent.com/assets/8938352/14587517/d287b388-04b4-11e6-9d8e-c33d4d64d3aa.png)
and 
![image](https://cloud.githubusercontent.com/assets/8938352/14587520/dd083b98-04b4-11e6-8968-7bf569313dd1.png)

is it those that you want to be css seperated?

**Comment by trumpy81** [comment]
Yes, those two elements, please :)

**Comment by dagalufh** [comment]
I've added select and input tags to the default.css file so they are in there forced to black text, white background. But that can of course be overwritten in other themes. But they are getting their setting from that tag and not from any inheritance now. I'll let you know when i've uploaded this fix.

Gonna do some more things first.

**Comment by dagalufh** [comment]
Download latest and try from my branch; https://github.com/dagalufh/WebTools.bundle/tree/micke-work

**Comment by trumpy81** [comment]
That's great news. It will give us a little more flexibility with colour choices. Thanks for that. :dart:

**Comment by dagalufh** [comment]
Let me know if you consider this solved and i'll close it. :)

**Comment by trumpy81** [comment]
I have not tested the new fixes, so it's hard for me to say yay or nay on that.

The issue with the default colors showing on buttons remains. As you can see in the following image, now it is not just the grey color showing but the default colour also.

I'm not sure what is causing it, if it's the browser or something else. It sure is strange though.

![untitled-1](https://cloud.githubusercontent.com/assets/12381786/14594375/23b22d64-0579-11e6-8c09-72043edcd223.jpg)

**Comment by dagalufh** [comment]
Hmm, a button uses:
btn-default
btn-default:focus
btn-default:hover
btn-active

Is it someone of those that are missing? Do an inspect on the button that is not showing what you want. There you can see what CSS it has. (At least this is in Chrome, i haven't used FF in about 7 years)

**Comment by trumpy81** [comment]
OK, I thought this may have been an issue with Win10 but I just did a reboot and the issue is still there in FF, Edge and IE 11. 

When you enter the UAS the 'All' button shows with the default CSS colours, the rest shows with the correct skin colours. If you click anywhere on the screen, the default colours disappear and revert to the current skin colours.

It happens with any skin selected in any browser.

![untitled-1](https://cloud.githubusercontent.com/assets/12381786/14594551/0569796e-057b-11e6-8be6-d93b686b58ed.jpg)

**Comment by dagalufh** [comment]
Ah, sounds like the :focus or :active

I set All button to focus after refresh. However, that might not be needed anymore, i'll investigate that. But in CSS, try setting btn-default:focus or btn-default:active

**Comment by trumpy81** [comment]
There is no css for btn-default:focus in the 'custom.css' file. I can add that and try it though.

Added .btn-default:focus {background-color: #f6894b; color: #68452c;}

But no change. the default colours still display.

**Comment by trumpy81** [comment]
could it be another cache issue? When you first start WebTools, the default style sheet is used, could it be that because it is cached, then when the override style sheet is used, the default style sheet is still in focus or something to that effect?

**Comment by dagalufh** [comment]
Custom.css is not the one you should look in. If you look at my branch, there is no such file. default.css is the most recent and valid one.

The default.css contains this: .btn-default:focus {background-color: #FE9B00; color: #242424;}

And upon starting, yes default is used. It goes to the selected upon logging in. I've thought about changing that but have not yet done so.

Default.css is always loaded. When you have a custom theme, it overrides the corresponding settings in default, but if a specific setting it not made in the custom theme, default still applies.

**Comment by trumpy81** [comment]
So, I added .btn-default:focus {background-color: #f6894b; color: #68452c;} and changed it .btn-default:focus {background-color: #ffffff; color: #000000;}

And now the issue appears to be gone for the UAS and the search buttons or at least they return to the default black and white colors which is quite acceptable IMHO.

And yes the dreaded cache got me again ... grrrrrrr ... lol

I think we can close this one too now.

**Comment by dagalufh** [comment]
Great, glad it works for you and also, i really value all the feedback as it helps in a great way to make the system better.

However, the caching issue is not something i can work around i'm afraid. Will close this issue now.
