### ISSUE TITLE
Feature Requests - Hyperlinks to Buttons on Main Page +

### ISSUE THREAD

**Issue by trumpy81** [dagalufh/WebTools.bundle#167]
After logging in to WebTools the user is presented with the Main Page that contains three hyperlinks to the various tool pages under the Available Modules heading.

I would like to see those hyperlinks displayed as buttons in a similar fashion as those buttons found on the UAS page, if that is at all possible.

Also, the title link on the Main Menu Bar and on the Welcome header is spelled Webtools but in almost all other instances it is spelled WebTools. Could that be corrected please.

On the UAS page, I would also like to see the welcome message and the manual installer 'centred' on the page in a similar manner as shown in the attached image.

![untitled-1](https://cloud.githubusercontent.com/assets/12381786/14817417/9ed957ba-0bfa-11e6-8754-aea3470dda85.jpg)

**Comment by dagalufh** [comment]
Currently testing out the buttons instead of links on main page.
Centering of things, can be done via CSS so that is completly fine to do within the themes of you so wish. That just adds another nice thing to the themes.

**Comment by ukdtom** [comment]
Confirmed working
