### ISSUE TITLE
Create a User Guide

### ISSUE THREAD

**Issue by ukdtom** [dagalufh/WebTools.bundle#170]
Create a user guide, since we are starting to get complicated here ;-)

It'll be in ODT format, and converted to pdf as well.
We need to host it somewhere in the http dir, like http/help

Work is been done by 3.Party, aka @trumpy81

Thanks Andy

**Comment by ukdtom** [comment]
Added to my branch
URL needed for help menu, would be:
/manual/WebTools-User-Manual.pdf

**Comment by trumpy81** [comment]
You are both welcome, if you have any issues with the document, please tell me and I will make the necessary corrections ASAP.

**Comment by ukdtom** [comment]
Confirmed working in latest from the Swede
