### ISSUE TITLE
Failed fetching the logfilenames from the server.

### ISSUE THREAD

**Issue by 2wenty2wo** [dagalufh/WebTools.bundle#179]
Hi, I just updated from version 2.1 to 2.2.
After signing into Plex on the WebTools login page I get a popup message:

> **An error occured.**
> Failed fetching the logfilenames from the server. Reload the page and try again.
> If the error persists please restart the server.
> Contact devs on the Plex forums if it occurs again.
> ```Errorinfo:
> Requested URL: /webtools2?module=logs&function=list&filter=WebTools&_=1463297303271
> Error Code/Message: 500/Internal Server Error
```

I've restarted Plex Media Server and it gives me the same error message.

**Comment by ukdtom** [comment]
Please make a zip of the webtools logs, and upload

**Comment by ukdtom** [comment]
Ping

**Comment by ukdtom** [comment]
Closed due to lack of response
