### ISSUE TITLE
picks up interface with private ip. 

### ISSUE THREAD

**Issue by areyesjr** [dagalufh/WebTools.bundle#180]
Not sure where the I can where this variable is called.

**Comment by ukdtom** [comment]
Sorry, but please rephrase question, cuz. I simply don't get it

**Comment by areyesjr** [comment]
Sorry for not providing all the info. When I installed WebTools it automaticly picked up the private IP adress of my server therefore I could not connect to it . I had to VNC into my linux server and then I was able to run WebTools. Not sure if its supposed to work like that but it would be cool if one could change that IP address that WebTools is listening on. The same way how you allow to change the port.

**Comment by ukdtom** [comment]
WebTools is bound to all IP addresses on the server.
The dialog is simply a guide for about 95% of the users out there ;-)
