### ISSUE TITLE
Error Installing Plug-Ins and Viewing Log

### ISSUE THREAD

**Issue by lopezj1** [dagalufh/WebTools.bundle#182]
I am using version 2.2.  Whenever I try to install a plug-in through UAS, I get the following error message.  But when I navigate back to PMS, the channel does appear, but then get error "this channel is not responding".  Also if I go back to UAS it looks like the plug-in was never installed when I filter showing only installed.

UAS Error when installing Plug-in
![screen shot 2016-06-22 at 7 57 30 pm](https://cloud.githubusercontent.com/assets/18203036/16287758/9f16c84e-38b3-11e6-83f0-1f523cb457e1.png)

Plug-in appears in PMS but channel doesn't work
![screen shot 2016-06-22 at 8 00 07 pm](https://cloud.githubusercontent.com/assets/18203036/16287818/0b20c31e-38b4-11e6-8665-49c65e9274d9.png)

UAS Does not show any installed plugins
![screen shot 2016-06-22 at 8 01 42 pm](https://cloud.githubusercontent.com/assets/18203036/16287831/2c3c8d94-38b4-11e6-9ff1-6386d839f781.png)

I also cannot open the logviewer/downloader tool.  There is an error message that pops up for a split second then screen goes dark and is disabled
![screen shot 2016-06-22 at 8 03 13 pm](https://cloud.githubusercontent.com/assets/18203036/16287850/67db937c-38b4-11e6-84a1-feea0a3e0725.png)

Any help would be appreciated.  I am using UAS in chrome browser.

**Comment by dagalufh** [comment]
Can you give us the logfiles from WebTools?
Den 23 juni 2016 02:05 skrev "lopezj1" <notifications@github.com>:

**Comment by lopezj1** [comment]
How can I access the logfiles?  The logviewer in UAS doesn't work.  Is there a file in the plug-ins folder that I can share?

**Comment by ukdtom** [comment]
https://github.com/dagalufh/WebTools.bundle/wiki/Troubleshooting

**Comment by lopezj1** [comment]
@ukdtom Thanks for that

Here is the file:
[com.plexapp.plugins.WebTools.log.zip](https://github.com/dagalufh/WebTools.bundle/files/332611/com.plexapp.plugins.WebTools.log.zip)

**Comment by ukdtom** [comment]
Sadly, you only provided one log fil, so I can sadly only see the problem with the logs!

Try this.....

Open the file named webtools.bundle/contents/code/logs.py

Then locate line 31, that looks like:
`if not os.direxists(self.LOGDIR):`

Change that to:

`if not os.isdir(self.LOGDIR):`

Then report back, as well as also upload new logs, and this time all of them for WebTools

**Comment by lopezj1** [comment]
That did not work for me.  Attached is zip folder

Thanks

[Plex Media Server.zip](https://github.com/dagalufh/WebTools.bundle/files/332887/Plex.Media.Server.zip)

**Comment by ukdtom** [comment]
This is very odd, cuz it seems like it's refusing to use build-in functions of python?

Scratching head here....

And the UAS problem seems to relate to the initial cache of the UAS repo

In the menu above, try and do a factory reset.
Then report back

**Comment by ukdtom** [comment]
And had fat fingers as well....

make

`os.isdir`

into
`os.path.isdir`

/T

**Comment by ukdtom** [comment]
Committed a small fix for the log issue https://github.com/dagalufh/WebTools.bundle/commit/8174e52be18697aedd31e03442f6e440aec9bcd2

**Comment by lopezj1** [comment]
I changed the code on line 31 and did factory reset and now am finally able to install channels with no error messages! Thanks alot for the help.  Now just have to figure out which channels work
