### ISSUE TITLE
500 Internal Server Error on every single action

### ISSUE THREAD

**Issue by Belazor** [dagalufh/WebTools.bundle#183]
Hi there,

There appears to be a critical bug in v2.2 when running on Mac OS X 10.11.5 where the following code is missing from WebTools.bundle/Contents/Code/logs.py:
`		elif function == 'entry':
			return self.entry(req)`

Without this, every single action returns

> 500: Internal Server Error

With no log files to show as none are written.

After fixing this issue, the only remaining issue is that the "items per page" and "theme" settings display HTTP 404 in the console unless I manually save these defaults.

**Comment by ukdtom** [comment]
Could I get a zip of the webtools logs please....

And all of them?

**Comment by Belazor** [comment]
The logs will be "contaminated" by the fact that I fixed it myself, and there's also the fact that I said in my OP "With no log files to show as none are written".

Once I'm done installing the channels I want, I will purge the logs, undo the fix and give you this information.

**Comment by ukdtom** [comment]
Thanks.....

And also do note this

https://github.com/dagalufh/WebTools.bundle/commit/8174e52be18697aedd31e03442f6e440aec9bcd2

**Comment by Belazor** [comment]
After removing every trace I could find of this plugin from the Application Support directory, and downloading a fresh bundle before applying the change from that commit, I initially could replicate it before realising I had forgotten to remove the existing Plex logs.

When I repeated the steps I could no longer replicate it, except for the 404 error on the wt_csstheme call (http://192.168.0.16:33400/webtools2?module=settings&function=getSetting&name=wt_csstheme&_=1466872153081).

The log does appear to write correctly now.

That being said, I noticed one slight irregularity when I was in the log file directory. In the ~/Library/Logs directory, I had two log directories related to Plex; "Plex Media Server" with all the subdirectories you would expect, and a stand-alone "PMS Plugin Logs" directory. This latter directory does not get re-generated when I restart Plex Server after deleting it.

Is it possible that WT got confused after detecting both of those log directories and this somehow caused the issue described in the OP?
My Plex install is ~8 months old and I've been using the Trakt bundle for a while - I only found out about WT after wanting an easier way of updating Trakt.

**Comment by ukdtom** [comment]
The commit I ref. above, was indeed a fix for logs on Mac

Click on the link, and check out the change I made, if possible, since I haven't got a Mac, and as such, is coding blindfolded here ;-)

If possible, replace your current log.py file with the one I got here:
https://github.com/dagalufh/WebTools.bundle/blob/tommy-work/Contents/Code/logs.py

And then please report back

And would still love to see a zip of all the WT logs ;-)

**Comment by Belazor** [comment]
As I said, it's working just now. It wasn't working before, even _with_ the log change, and I thought maybe the two different log directories might be the cause of why. I don't know much python, I basically had to read up on the Tornado web server in order to figure out possible causes for the 500 ISE. 
I then had to guess that since it was only erroring out of the "entry" type, the line I showed in the OP must have been the cause.

Regardless, here's the log directory:
[Plex Media Server.zip](https://github.com/dagalufh/WebTools.bundle/files/333156/Plex.Media.Server.zip)

**Comment by ukdtom** [comment]
Could you tell me where in the file you added the line?

**Comment by Belazor** [comment]
Within `def reqprocess(self, req):` above `elif function == 'list':`

**Comment by ukdtom** [comment]
Huh....Entry is supposed to be a Post, and not a Get

Assigning to frontend dev :-)

**Comment by Belazor** [comment]
It was, but it was still causing issues:
http://i.imgur.com/jwweemS.png
http://i.imgur.com/AGztMdk.png

Those are screenshots I took prior to investigating the Tornado web server and adding that line.

**Comment by ukdtom** [comment]
Your change in this case simply doesn't compute, since you changed how the log module reacts during a get, but your screen dumps shows correctly a post?

Extremely confused here

**Comment by Belazor** [comment]
I've no idea either, all's I know is I was sat there for an hour googling for this problem and nothing worked, until I added that line.

But it isn't required as it works fine with only the path change you linked to, so I've no idea why this happened.

Hopefully either this was just a fluke or someone else who's better at troubleshooting has the same issue, I'd be okay with you closing this as not a bug :)

**Comment by ukdtom** [comment]
Telling my swedish friend to stand down then ;-)
