### ISSUE TITLE
eFukt bundle doesn't show

### ISSUE THREAD

**Issue by ukdtom** [dagalufh/WebTools.bundle#187]
But is in the dict?

https://github.com/ukdtom/UAS2Res/pull/25#issuecomment-231665678

**Comment by NotVinny** [comment]
It's showing up for me, but it's at the bottom of the list instead of being in alphabetical order. The beeg channel does the same thing for me.

**Comment by dagalufh** [comment]
Fix implemented in my dev branch.

**Comment by ukdtom** [comment]
Confirmed working
