### ISSUE TITLE
[windows] Can't use LogViewer - 500 error, possible encoding issue

### ISSUE THREAD

**Issue by dein0s** [dagalufh/WebTools.bundle#190]
Sad to come back here today again, but it seems that my problems doesn't end after #189.
Theme manager and UAS looks fine for now, but can't use LogViewer.
OS: Windows 10 x64
System-Wide language: Russian
Codepage: 1251
Locale: 1251

![k9spqcm 1](https://cloud.githubusercontent.com/assets/7908313/16842232/5c0cdc8a-49e5-11e6-857a-bb4c254e23f1.png)

```
2016-07-14 17:11:27,227 (600) :  DEBUG (logkit:13) - Fatal error happened in Logs show: 'utf8' codec can't decode byte 0xce in position 94: invalid continuation byte
```
Code reference:
`Contents.Code.logs.logs#show:123`

Worth to mention, that it works fine on my virtualbox with Linux Mint 18 and utf-8 by default.

[wt_log_logviewer_error.zip](https://github.com/dagalufh/WebTools.bundle/files/363960/wt_log_logviewer_error.zip)

**Comment by ukdtom** [comment]
You are not the only one sorry here ;-)

Could I get a zip of the Plex Media Server.log please

**Comment by dein0s** [comment]
Sure.
[pms_log.zip](https://github.com/dagalufh/WebTools.bundle/files/364081/pms_log.zip)

**Comment by dein0s** [comment]
Guess, that lines like this can be the reason.
```
Jul 14, 2016 17:32:18.524 [3808] DEBUG - NetworkInterface: ignoring adapter 'РџРѕРґРєР»СЋС‡РµРЅРёРµ РїРѕ Р»РѕРєР°Р»СЊРЅРѕР№ СЃРµС‚Рё* 2' 
```

Can't imagine, that I'm the only one, who facing such encoding problems with plex.
But found almost nothing usefull on the official forum. Feels bad :|

**Comment by ukdtom** [comment]
^^ Think so as well regarding the line.
And when trying your file on my box, it claims the file can't be found....
Puzzled here, so might take a while

**Comment by ukdtom** [comment]
logs.py file

Do an import like:
import codecs, locale


Then find line:

```
			with codecs.open(file, encoding=locale.getpreferredencoding(), errors='ignore') as content_file:
#			with io.open(file, 'rb') as content_file:
```

Then please report back

**Comment by dein0s** [comment]
Still 500, but now with another reason
`Fatal error happened in Logs show: builtins_open() takes at most 2 arguments (3 given)`

**Comment by ukdtom** [comment]
Care to try the early alpha of the next version instead?
https://github.com/dagalufh/WebTools.bundle/archive/tommy-work.zip
And FindMedia is not yet working on the Windows platform, but should work on Linux

**Comment by dein0s** [comment]
Sure, why not.
Anyway I'm too nervous today for writing own code :D

**Comment by ukdtom** [comment]
LOL

**Comment by ukdtom** [comment]
And do report back regarding the logviewer

**Comment by dein0s** [comment]
On alpha also same 500 as in previous comment
```
2016-07-14 19:13:15,194 (20b4) :  CRITICAL (core:574) - Fatal error happened in Logs show: builtins_open() takes at most 2 arguments (3 given) (most recent call last):
  File "C:\Users\dein0s\AppData\Local\Plex Media Server\Plug-ins\WebTools.bundle\Contents\Code\logs.py", line 139, in show
    with codecs.open(file, encoding=locale.getpreferredencoding(), errors='ignore') as content_file:
  File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\codecs.py", line 881, in open
    file = __builtin__.open(filename, mode, buffering)
TypeError: builtins_open() takes at most 2 arguments (3 given)
```
[alpha_pms_wt_logs.zip](https://github.com/dagalufh/WebTools.bundle/files/364265/alpha_pms_wt_logs.zip)

**Comment by dein0s** [comment]
God damn, why they just can't provide full version of current 2.7.x python? Will take another ~50 mb uncompressed, but will solve so much problems.

I remember that day, when I tried to get type of some variable. I was like O_O, wtf?
And few minutes later, when I just gave up, it was looking like
```
if isinstance(a, dict):
    print 'HOORAY'
```

**Comment by ukdtom** [comment]
Try this in the log.py file:

```
#			with codecs.open(file, encoding=locale.getpreferredencoding(), errors='ignore') as content_file:
			with io.open(file, 'r+', errors='ignore') as content_file:
```

And believe it or not, but codec.open behaves differently in Plex on Windows compared to Linux..:SIGH....

**Comment by ukdtom** [comment]
And has to stop for a while......Dinner time ;-)

**Comment by dein0s** [comment]
Take your time, I'm not in a hurry :)
And, for sure, I belive you. Happened to me also few times.

I'm getting permission restriction even when running PMS as admin with :
```
with io.open(file, 'r+', errors='ignore') as content_file:
```

Log:
```
2016-07-14 19:46:33,762 (1c68) :  CRITICAL (core:574) - Fatal error happened in Logs show: [Errno 13] Permission denied: u'C:\\Users\\dein0s\\AppData\\Local\\Plex Media Server\\Logs\\Plex Media Server.log' (most recent call last):
  File "C:\Users\dein0s\AppData\Local\Plex Media Server\Plug-ins\WebTools.bundle\Contents\Code\logs.py", line 138, in show
    with io.open(file, 'r+', errors='ignore') as content_file:
IOError: [Errno 13] Permission denied: u'C:\\Users\\dein0s\\AppData\\Local\\Plex Media Server\\Logs\\Plex Media Server.log'
```

**Comment by ukdtom** [comment]
I made an error here....SIGH.....

In the line with io.open, change 'r+' into 'r'

Then please report back

**Comment by dein0s** [comment]
Yep, you are right. Figured it ouy few mins ago.
Also, take a look `Contents.Code.logs.logs#download:134`. As I see, it needs same changes here.

**Comment by ukdtom** [comment]
Indeed, and fixed with https://github.com/dagalufh/WebTools.bundle/commit/39c1d17b5250927cd0cff9ef907cf4c5d758771e

**Comment by ukdtom** [comment]
And now wondering......Got any sidecar subs, in russian, that perhaps also breaks, when viewing in the subtitle module?

**Comment by dein0s** [comment]
On a first glance - nope. 
But, to be honest, not yet tried to go in deeps of it, because mostly using plex for watching tv shows on-line (from russian online portal) and twitch.tv (their native app for android tv sux a lot).
Aimed mostly for LV in WT under windows, because I'm too lazy to load vb everytime for debugging if I'm not in dev mode :D

But, for sure, will take a look at subs and findmedia in a free time.
