### ISSUE TITLE
Infinite loading circle

### ISSUE THREAD

**Issue by Milkbone** [dagalufh/WebTools.bundle#192]
After installing the plugin I can never get the Web ui to load. I've tried restarting, reinstalling and http/https both. Nothing works. I use a appbox from bytesized-hosting.com

**Comment by ukdtom** [comment]
We'll need logs please

**Comment by Milkbone** [comment]
Here are the logs for the http://pastebin.com/CbCCwb4r com.plexapp.plugins.WebTools.log

**Comment by ukdtom** [comment]
Looks 100% normal.
And WebTools is simply waiting for a req.

Are you sure, that your hosting company allows access to port 33400?

**Comment by Milkbone** [comment]
I'll check with my host to see the available ports I can switch too and get back to you if that fixes it. 

Thanks for the help

**Comment by ukdtom** [comment]
You're welcome.
Closing for now, and if it turns out that's not the issue, then feel free to reopen
