### ISSUE TITLE
ImportError: No module named plex2csv_moviefields - In Centos

### ISSUE THREAD

**Issue by ashishsoni** [dagalufh/WebTools.bundle#193]
Just downloaded the latest master and getting below error
ImportError: No module named plex2csv_moviefields

Please help

**Comment by ukdtom** [comment]
Please go here:

https://github.com/ukdtom/plex2csv.bundle/issues

And attach Plex2CSV logfiles when creating the incident

**Comment by ukdtom** [comment]
Sorry, closed by a mistake ;-)

Please upload a zip of all the WebTools logs

**Comment by ashishsoni** [comment]
Got it working in i placed the bundle in /usr/lib instead of /var/lib now working thanks
