### ISSUE TITLE
Error when deleting agent subtitles

### ISSUE THREAD

**Issue by brossow** [dagalufh/WebTools.bundle#194]
Using Plex Media Server 1.1.4.2757 (also happens with 1.1.3.2700) on my Mac Pro (10.11.6) and WebTools 2.2, when I try to delete a subtitle added by an agent, I get the following error:

`{"readyState":4,"responseText":"Fatal error happened in delSub: bad argument type for built-in operation","status":500,"statusText":"Internal Server Error"}`

**Comment by ukdtom** [comment]
Ful WebTools logs please, and which agent?

**Comment by ukdtom** [comment]
Ping

**Comment by ukdtom** [comment]
Closed due to lack of response

**Comment by ukdtom** [comment]
https://github.com/dagalufh/WebTools.bundle/issues/197
