### ISSUE TITLE
plugins plex torrent streaming free HD

### ISSUE THREAD

**Issue by chocolatesuper** [dagalufh/WebTools.bundle#195]
you put plugins torrents to see movies and free series 2016 full hd thank you very much as a Similary to bittorrent plex much better yts eztv

**Comment by ukdtom** [comment]
I do not test 3Party, so no idea what they do, I only check if they install

**Comment by chocolatesuper** [comment]
@ukdtom There are problems with the servers webtools  I try to install the plugins I errors  help me

**Comment by ukdtom** [comment]
Need both info about PMS version, OS as well as a zip of the WebTools logs!

**Comment by chocolatesuper** [comment]
yes

**Comment by chocolatesuper** [comment]
An error occured, please check the logs.

Errorinfo:
Requested URL: webtools2?module=git&function=getGit&url=+%09https%3A%2F%2Fgithub.com%2Fmikedm139%2FCouchPotato.bundle+
Error Code/Message: 500/Internal Server Error

**Comment by ukdtom** [comment]
I need logs, not a screenshot!

**Comment by chocolatesuper** [comment]
An error occured, please check the logs.

Errorinfo:
Requested URL: webtools2?module=git&function=getGit&url=%09https%3A%2F%2Fgithub.com%2Fmikedm139%2FCouchPotato.bundle+
Error Code/Message: 500/Internal Server Error

**Comment by ukdtom** [comment]
https://github.com/dagalufh/WebTools.bundle/wiki/Troubleshooting

**Comment by ukdtom** [comment]
See if WebTools log module can download all logs first though

**Comment by ukdtom** [comment]
And still need info about PMS version, as well if you are running Windows, some kinda Linux, or Mac!

**Comment by chocolatesuper** [comment]
mac os x

**Comment by chocolatesuper** [comment]
yes

**Comment by chocolatesuper** [comment]
update version v2.3 webtools

**Comment by ukdtom** [comment]
Huh...2.3 is NOT released, and NOT working!!!!

And still need logs!

**Comment by ukdtom** [comment]
Released version is found here:

https://github.com/dagalufh/WebTools.bundle/releases/latest

**Comment by chocolatesuper** [comment]
ok thank you
