### ISSUE TITLE
Wrapping needed in GUI dialog

### ISSUE THREAD

**Issue by ukdtom** [dagalufh/WebTools.bundle#202]
When deleting a sub, the path is not wrapped correctly, so it goes beyond the bounding of the popup box

![wrapping needed](https://cloud.githubusercontent.com/assets/4699449/19457581/3baea252-94c7-11e6-961d-1f66e5a13765.png)

**Comment by dagalufh** [comment]
Fixed in next commit.

**Comment by dagalufh** [comment]
![image](https://cloud.githubusercontent.com/assets/8938352/20940918/b41e31ea-bbf4-11e6-9514-2af5899b0a5c.png)

**Comment by ukdtom** [comment]
Confirmed
