### ISSUE TITLE
UAS: Channel Update from manual app installer broken

### ISSUE THREAD

**Issue by Twoure** [dagalufh/WebTools.bundle#214]
When a channel is installed by the _manual app installer_ the `branch` is set to `''` ([git.py#L368](https://github.com/dagalufh/WebTools.bundle/blob/master/Contents/Code/git.py#L368)), which was fine in the past, but now v2.3 requires a `branch` when updating the channel, or using the update all channels feature ([git.py#L223-L253](https://github.com/dagalufh/WebTools.bundle/blob/master/Contents/Code/git.py#L223-L253)).

**Example:** [git.py#L250](https://github.com/dagalufh/WebTools.bundle/blob/master/Contents/Code/git.py#L250)
`Dict['installed'][bundle]['branch']` returns an empty string, causing a malformed URL.

**Side Note:** Re-using the migrate channels function does not auto-fill the missing branch info.

**Comment by ukdtom** [comment]
Not sure I get what you are saying here?

Doing a manual install of a bundle, not in UAS, will set the branch dir to master

Like this get shows:
`http://PMS_IP:33400/webtools2?module=git&function=list`

`{
    "https://github.com/jwsolve/Afdah.bundle": {
        "description": "",
        "title": "Afdah",
        "bundle": "Afdah.bundle",
        "CommitId": "55fb786bb9",
        "branch": "master",
        "date": "2016-10-26 19:30:19",
        "identifier": "com.plexapp.plugins.afdah",
        "type": [
            "Unknown"
        ],
        "icon": ""
    }
}`

However, if doing a "Factory Reset", will make WebTools loose track of the install source, when migrated back in, and has always been so.

Is that what you perhaps is seen?

**Comment by Twoure** [comment]
Sorry, you are right.  The current version (and possibly the previous version) will set the `branch` to `master` when using the _manual app installer_.

My issue may be from an older version of the WT (I guess).  For some reason all of my previously manually installed channels do not have the branch set.  They are all GitHub channels that are not included within the UAS _(hence manual)_.  I can go though each one and remove them, then re-add them so the `branch` is set properly, but is a pain _(as I have ~45 manually installed channels)_.  Especially when some of those channels have `Dict` data I'd like not to lose.

Note:
- I've never preformed a WT "Factory Reset"
- Installed WT once, (at v2.0), and updated manually until the new WT updater, then used the internal updater only

**Comment by ukdtom** [comment]
I'll see what I can do here ;-)

**Comment by ukdtom** [comment]
And would it be possible for you to post a dump of your current dict?
Just if anything else is missing here

**Comment by Twoure** [comment]
> And would it be possible for you to post a dump of your current dict?

Yes: [wt-dict.zip](https://github.com/dagalufh/WebTools.bundle/files/554471/wt-dict.zip)

**Comment by ukdtom** [comment]
Care to test the Issue-214 branch?

/T

**Comment by Twoure** [comment]
Tested the Issue-214 branch, but found [git.py#L244](https://github.com/dagalufh/WebTools.bundle/blob/issue-214/Contents/Code/git.py#L244) was `True` for my affected bundles.  Fixed the fix in a pull request https://github.com/dagalufh/WebTools.bundle/pull/217 :wink:.  I understand not using the pull and just editing the file yourself.

**Comment by ukdtom** [comment]
Fix checked into https://github.com/dagalufh/WebTools.bundle/commit/a45d8f98fc8f893129a3d223648ac8570fc1ea9d
