### ISSUE TITLE
Menu issue

### ISSUE THREAD

**Issue by ukdtom** [dagalufh/WebTools.bundle#215]
Select Sub module, and a menu item appears named "Libraries"

Now select another module from the menu, and Library menu is still visible

**Comment by dagalufh** [comment]
I will look into this.

Den 26 okt. 2016 20:12 skrev "Tommy Mikkelsen" <notifications@github.com>:

**Comment by dagalufh** [comment]
Fixed in next commit.

**Comment by ukdtom** [comment]
Confirmed
