### ISSUE TITLE
modules

### ISSUE THREAD

**Issue by michaeldrivas1** [dagalufh/WebTools.bundle#229]
3 Attempts with shutting server off and I'm still getting this mess..........

Failed activating the module. Reload the page and try again.
If the error persists please restart the server.
Contact devs on the Plex forums if it occurs again.
Errorinfo:
Requested URL: modules/subtitlemgmt/jscript/subtitlemgmt.js?_=1483931721478
Error Code/Message: 404/Not Found

**Comment by ukdtom** [comment]
Sounds like a faulty install.

What OS are you on?

**Comment by michaeldrivas1** [comment]
Thx..... Running the latest Windows 10 pro 64 bit desktop version...

**Comment by michaeldrivas1** [comment]
Just got it.... I had too many open servers on at the same time... I believe they might have been causing interference...  Thank you!
