### ISSUE TITLE
uas and categories

### ISSUE THREAD

**Issue by ukdtom** [dagalufh/WebTools.bundle#64]
Beta tester would like a category named "All"

**Comment by dagalufh** [comment]
This in extension means a pagingsystem also. So this will take some time to implement.

**Comment by dagalufh** [comment]
Category implemented, Will look into pagingsystem..

**Comment by dagalufh** [comment]
Implementation uploaded to micke-work branch. Includes:
New category, All.
Pagesystem
Options for supporting above pagesystem.
