### ISSUE TITLE
No information included on how to use the Subtitle Manager

### ISSUE THREAD

**Issue by trumpy81** [dagalufh/WebTools.bundle#73]
It would be nice to have a short instruction on how to use the Subtitle Manager when you reach the Subtitle Manager page.

At present, it is very easy to miss the additional Top Menu item and there are no links or clues to tell one what to do, so it looks like the Subtitle Manager is unfinished/non functional at first glance.

Just needs a 'Look Up Dummy' type blurb on the landing page. :)

Thanks.

**Comment by dagalufh** [comment]
Sounds reasonable, I will try to write something usefull. Thanks for the feedback! :)

**Comment by trumpy81** [comment]
No problem. This is a great tool and kudos to all involved in putting it together. :)

**Comment by dagalufh** [comment]
Added short headsup in last update.

**Comment by trumpy81** [comment]
Excellent, new blurb should help alleviate any confusion ... lol

This can probably be closed.
