### ISSUE TITLE
Page selector in Subtitle Manager covers screen

### ISSUE THREAD

**Issue by trumpy81** [dagalufh/WebTools.bundle#75]
When using the Subtitle Manager and one selects a large Movie library, the page selector at the bottom of screen covers a large area of the screen. See the attached image.

That needs to be changed to a drop down selector on the Top Menu IMHO, or allow a user to type in a page number in order to select the desired page.

Or alternatively, use an alphabet type selector with 0-9 & A-Z selectors.

![untitled-1](https://cloud.githubusercontent.com/assets/12381786/12059146/4c0ccf86-afa1-11e5-8cce-68bc3acd3e1e.jpg)

**Comment by ukdtom** [comment]
Heh.....Wonder how this would look on a cellphone :-)

**Comment by trumpy81** [comment]
Would you even be able to view it on a cellphone?

**Comment by dagalufh** [comment]
Yes, entire webtools is made to also work from phones. 

Regardin high amount of pages, good catch. I will fix this. Will most likley be a next, previous button and a drop down in the middle with pagenumbers. 

Either all the time or only when pages>10 or something.

**Comment by trumpy81** [comment]
That sounds like a better solution :)

**Comment by dagalufh** [comment]
Fixed in next version.
