### ISSUE TITLE
Subtitle Manager - TV Show library does not list all

### ISSUE THREAD

**Issue by trumpy81** [dagalufh/WebTools.bundle#76]
When using the Subtitle Manager and you select a TV Show, only the first 15 or so TV Shows are listed and no scroll bar appears to allow you to scroll through the entire list.

The page selector works however ... Doh!

That does make things seem a little disjointed, especially if you come straight from a Movie library listing where a scroll bar is present and operable.

See the attached image.

![untitled-2](https://cloud.githubusercontent.com/assets/12381786/12059251/8894cd1c-afa3-11e5-8d90-e0c1fe6e1be7.jpg)

**Comment by dagalufh** [comment]
That is a works-as-designed. You have the items per page on 15, that applies to tv show listing also. As you can see on the bottom, you have 8 pages in total.

However, not sure if this needa to be split into pages. But it is to support those with large libraries so they don't have a huge list to scroll through.

**Comment by trumpy81** [comment]
Yeah, but compared to all other sections, the TV Shows is handled very differently, which can be confusing for first time users or silly old buggers like me.

I am kind of hoping that it can be brought into line with the other sections a little more to save on the confusion and to provide a more integrated feel to the app.

Of course I realise there needs to be differences because it is a TV Show list, I just feel it needs some work is all.

As it is, it does work well enough, just not as expected when compared to other sections..

**Comment by ukdtom** [comment]
TV-Shows are handled internally different by PMS as well, since we for shows has:
[show-season-episode]

For a movie section, we have
[movie]

As such, and since some shows tends to be very large, like the Simpsons etc, we have to page, in order not to stress the PMS

So as dagalufh said, it's WAD, and paging is a req. I forced into the webTools api

/T

**Comment by trumpy81** [comment]
This is not about the 'paged' nature of the display, it is about the lack of a scroll bar. How will that effect usage on a phone for example?

Movies are also paged, but they do have a scroll bar also, which is what I expected in the TV Shows as well.

**Comment by dagalufh** [comment]
If i minimize the windows to the point where 15 rows don't fit, a scrollbar appears.
Does this not happen for you?

**Comment by ukdtom** [comment]
Sorry, then I read it wrong here ;-)

**Comment by trumpy81** [comment]
@dagalufh Yes it does, but it only scrolls 15 entries per page, it should be able to scroll through all of the list, from the first TV Show to the Last TV Show, if you know what I mean?

**Comment by dagalufh** [comment]
Yes, under Options you have the possibility to set the amount of pages to view on a page.
That effects both tv shows and movies.

**Comment by trumpy81** [comment]
OK, I missed that option ... doh!

I guess this can be closed then. :)
