### ISSUE TITLE
SM - Overall Layout

### ISSUE THREAD

**Issue by trumpy81** [dagalufh/WebTools.bundle#83]
New layout for Movies is much improved, thank you. I like the new page selector. ;)

However, a few things come to mind.

1. Yellowish text on White background is difficult to read in the page selector.
2. Cursor changes to the text bar when mouse pointer is over previous or next buttons.
3. Page box is of different dimension to surrounding text boxes/buttons. (not a big deal ;)
4. Could probably use this style for TV Shows also.

**Comment by dagalufh** [comment]
Number 4, what do you mean? They share most of the style.

**Comment by trumpy81** [comment]
Perhaps I am simply not seeing it due to the number of listings, but when I am in a TV Show list the page numbers at the bottom of the window are in separate boxes.

When in a Movie listing, I see the page selector (a list selector) with the page numbers and also a next button if on the first page, and with a previous button if I am not on the first page.

Movie List:
![movielist](https://cloud.githubusercontent.com/assets/12381786/12087327/c4693b48-b31d-11e5-9ce5-52b75b67bab0.jpg)

TV Show List:
![tv-show-list](https://cloud.githubusercontent.com/assets/12381786/12087336/d103cd8c-b31d-11e5-9817-26e5cf851146.jpg)

**Comment by trumpy81** [comment]
It doesn't show the page selector until there is more than 10 pages. With less than 10 pages, they are listed in separate boxes.

Sorry, I did not see that behaviour before because it always showed less than 10 pages. You can ignore number 4.

**Comment by dagalufh** [comment]
Alrighty. I'll look into the other. Change the cursor on hover and such. Perhaps also increase the size of the other page buttons.

**Comment by trumpy81** [comment]
No problem. And my apologies, I should have checked and changed the number of entries in the list, but I simply did not think of that and since I use dual monitors I always have everything full screen ... lol

**Comment by dagalufh** [comment]
Thoughts on the changes?

**Comment by trumpy81** [comment]
1. Definitely better than before, not sure I like the colour scheme though. Too much yellow/orange.
2. Fixed, thank you :)
3. Not a big deal but the buttons do look out of place a bit size wise. Maybe just add a small space between the list selector and the buttons??
4. delete ... lol

**Comment by dagalufh** [comment]
1. I can think about another theme but i can't promise anything.
2. Good
3. Fixed in upcoming commit.

**Comment by trumpy81** [comment]
Sounds like you have everything covered so I will go ahead and close this.

Thanks for the great response and for putting this tool together with Tommy. I am looking forward to it's release as it should be a handy tool for all users of Plex. :)
