### ISSUE TITLE
SM - Feature Request - Add/delete embedded subtitles

### ISSUE THREAD

**Issue by trumpy81** [dagalufh/WebTools.bundle#84]
This would be super nice to have, but probably super hard to achieve.

If it is possible at all, at least being able to delete embedded subtitles would be a nice feature.

Being able to add embedded subtitles, only from any existing external subtitles, would be good too.

I realise there are probably limitations to what can be done, but this is something for a possible future function maybe.???

**Comment by ukdtom** [comment]
Manipulation of embedded srt's would req. us to remux, aka altering peoples medias, and not in scope, nor will be.....

Even crossing the barrier, and deleting external (sidecars) srt's is risky, and as far as we'll go
