### ISSUE TITLE
WT - No version/sub version number

### ISSUE THREAD

**Issue by trumpy81** [dagalufh/WebTools.bundle#85]
Version numbers of some kind need to be displayed somewhere in the app, either on the title bar (best place) or from one of the menus (options perhaps?) so that one can report what version of the plug-in they are running.

Even though this is still beta, it would probably be an idea to get that happening now so that you don't have to worry about it later on. ;)

**Comment by ukdtom** [comment]
When we release, version numbering will be restricted to x.y, and will be incremented for every release, but see the point here for beta's.....

@dagalufh: Thought?

**Comment by trumpy81** [comment]
It's still nice to know what beta you are running, just in case you didn't update when you should have.

**Comment by ukdtom** [comment]
True

**Comment by dagalufh** [comment]
I will atleast try to write in the changelog. There it will be the date of the checkin that will be the reference.

**Comment by ukdtom** [comment]
Cool, cuz since you now handle the changelog file, I'll assign it to you :-P

**Comment by dagalufh** [comment]
Fixed
