### ISSUE TITLE
LV - Possibly omit zero length log files from list

### ISSUE THREAD

**Issue by trumpy81** [dagalufh/WebTools.bundle#86]
The DLNA Server Neptune log files are often empty, with a file size of zero, so they probably do not need to be listed in the log file selector.

Thoughts?

**Comment by ukdtom** [comment]
Hmmm....Could cause confusion, if like log.4 has contents, 3 hasn't, and 2 and one has....

Then we might get crawled with Q's about missing from the listing.

**Comment by trumpy81** [comment]
Yeah good point. I will leave it up to you, just thought it was worth mentioning.

**Comment by ukdtom** [comment]
And it was, but think we'll keep that as is
