### ISSUE TITLE
UAS - Previous plug-ins not recognised

### ISSUE THREAD

**Issue by trumpy81** [dagalufh/WebTools.bundle#88]
When installing WebTools for the first time, any previous plug-ins, such as Find Unmatched, are not recognised and when installing the same plug-in from the UAS, the old plug-in remains in the Plug-ins folder.

In the case of Find Unmatched a folder named FindUnmatched.bundle already existed in the plug-ins folder. After installing Find Unmatched with UAS, it added a folder named Plex-FindUnmatched.bundle.

In the case of plex2csv a folder named plex2csv.bundle already existed. After installing from UAS, the folder remained and the timestamp for the folder remained unchanged.

This could potentially cause a problem in Plex or for the plug-in. Perhaps a warning of this issue should be presented in the GUI somewhere?

Also, currently, there is no timestamp displayed in UAS for the 'Latest Update on Github:  - '

**Comment by ukdtom** [comment]
That's what the migrate function is for....

Should be outlined for you in the text of the main UAS screen, or?

**Comment by trumpy81** [comment]
Argh, OK, that makes sense now .... lol

It helps if you read the blurb at the top of the page too .... doh!

Closing.

**Comment by ukdtom** [comment]
And the missing timestamp will be there, if you click on the "Check for updates" button

**Comment by trumpy81** [comment]
Another Doh!!! .... I knew that ... lol
