### ISSUE TITLE
Migrated bundles and update

### ISSUE THREAD

**Issue by ukdtom** [dagalufh/WebTools.bundle#89]
If a migrated bundle is not part of the UAS, I try to fetch http://plugin identifier, which will fail!

**Comment by ukdtom** [comment]
And spotted by Andy....Thanks

**Comment by ukdtom** [comment]
Will now return 404 to the GUI

Related to Issue #90 and #80

**Comment by dagalufh** [comment]
Re-insall and check for updates has been disabled for these.
