### ISSUE TITLE
Migrated bundles and Repo url

### ISSUE THREAD

**Issue by ukdtom** [dagalufh/WebTools.bundle#90]
A bundle, that has a repo name not starting with http, should not be shown in the repo link.

STD: install the https://github.com/jwsolve/Afdah.bundle bundle, and then migrate

**Comment by ukdtom** [comment]
Repo link is still there?

Suggest, that it's hidden, when not starting with http
(With above, we cover both http and https)

**Comment by dagalufh** [comment]
![image](https://cloud.githubusercontent.com/assets/8938352/12138818/106aeb6a-b45c-11e5-947b-bea1544b2516.png)

Fixed in upcoming commit.

**Comment by ukdtom** [comment]
Workinf perfectly
