### ISSUE TITLE
UAS: offically installable plugins are migrated and 'quick jump to' fails for these

### ISSUE THREAD

**Issue by OttoKerner** [dagalufh/WebTools.bundle#91]
how to re-create:

install a officially available plugin via Plex Web - Channels (left side, above all libraries) - Install Channels
I used the 'Southpark' channel, which is available this way
open the UAS, 'migrate existing channels'
'Quick Jump to Bundle' - "South Park"

screen is dimmed down, and it eternally toasts "Loading, please wait."

**Comment by dagalufh** [comment]
I will check this tomorrow. Strange error.

**Comment by dagalufh** [comment]
Corrected in next commit.
