### ISSUE TITLE
[FrontEnd] Themes

### ISSUE THREAD

**Issue by dagalufh** [dagalufh/WebTools.bundle#93]
Perhaps add themes and a selector for those.

This will be if i can think of a good color theme.

**Comment by trumpy81** [comment]
I have a proposal which is just a few changes to the current scheme. I have not used the correct fonts in my example but I have included the colour codes.

![untitled-1](https://cloud.githubusercontent.com/assets/12381786/12124937/23793e82-b434-11e5-8da2-a3b851de21b2.jpg)

Any thoughts/comments are welcome.

**Comment by dagalufh** [comment]
Seems nice, i can toss something up with that.

**Comment by dagalufh** [comment]
Oh my... Look what i found ;)

![image](https://cloud.githubusercontent.com/assets/8938352/14504294/711282f2-01b4-11e6-8547-0eb0814a1076.png)

**Comment by trumpy81** [comment]
Thought I would upload some custom themes. Comments are welcome! :)

Had to work around the limitations noted in GHI #161, but hopefully these are OK.

[custom_themes.zip](https://github.com/dagalufh/WebTools.bundle/files/222284/custom_themes.zip)

**Comment by dagalufh** [comment]
I'll take a look at them, what do you think of the Theme selector?

**Comment by trumpy81** [comment]
Now that I have gotten past that silly FF issue ... it works great!! :dancer:

**Comment by dagalufh** [comment]
I've downloaded and i like it. :)

I noticed on the plex one that the modals are still in orange. Just a fyi. :)

**Comment by trumpy81** [comment]
Silly question, but where/when would I see the modals?

Do they only show up on a mobile device, because I did not do any checking on a mobile device at all.

**Comment by dagalufh** [comment]
Great :) I use Chrome when developing since that gives me the option to, when console is open, long press Refresh button to have it do a full clear of everything when reloading.

**Comment by ukdtom** [comment]
Checked in
